### ISSUE TITLE
Problem loading the plugin.

### ISSUE THREAD

**Issue by Chenterito** [fedddddd/iw5-gsc-utils#1]
I would like you to help me, I try to use the plugin to be able to set the same ClanTag to all the players, but when the server tries to load the plugin it gets this error:

![image0](https://user-images.githubusercontent.com/64875738/124543446-de80c980-ddea-11eb-84d0-c79015e1ef42.jpg)

**Comment by fedddddd** [comment]
Please post a proper screenshot along with the error code

**Comment by Chenterito** [comment]
Failed to load plugin

**Comment by Chenterito** [comment]
Failed to load plugin "iw5-gsc-utils.dll": 0x0000045A
![20210706_081154](https://user-images.githubusercontent.com/64875738/124605856-f6c80700-de31-11eb-91bf-9b7dc74c23fb.jpg)

**Comment by fedddddd** [comment]
That error indicates that a dll didn't correctly initialize (not the plugin itself), I think I had this error before on another machine and reinstalling visual c++ redistributables fixed it but I'm not completely sure.

**Comment by Nightmareland** [comment]
I'm getting the same error so I reinstalled visual c++ but the error is still there.
Which visual c++ should I install in particular then ? @fedddddd

**Comment by mjkzy** [comment]
download latest version and try again @Nightmareland
