### ISSUE TITLE
Failed to load plugin

### ISSUE THREAD

**Issue by Nightmareland** [fedddddd/iw5-gsc-utils#2]
Hello, I have this error but I already tried to reinstall visual c++ and it still doesn't work. 
How can I fix that ? @fedddddd 
![failed load plugin](https://user-images.githubusercontent.com/55696481/131391922-c19dd78a-a3c6-4c0a-bdfc-26ed3bebaa78.PNG)

**Comment by fedddddd** [comment]
Plugin needed to be updated
