### ISSUE TITLE
crashes server upon "scanning "AppData\Local\PLUTON~3\storage\iw5\plugins" for plugins..." line in terminal

### ISSUE THREAD

**Issue by QuikksterYT** [fedddddd/iw5-gsc-utils#27]
used to use this plugin all the time until one of the Plutonium updates broke it entirely, newest gsc utils release still has the same issue :(

crashes before the server can fully boot up, when loading the plugins folder

**Comment by fedddddd** [comment]
works perfectly fine for me

**Comment by Chenterito** [comment]
The same happens to me. What dependencies does the plugin use?
