### ISSUE TITLE
onPlayerSay  issues theres a few ive noticed

### ISSUE THREAD

**Issue by swifty-tekno** [fedddddd/iw5-gsc-utils#7]
EDIT:  (I did a work around by print the say log myself in say callback when hiding chat
`logPrint("say;" + self.guid + ";" + self getEntityNumber() + ";" + self.name + ";" + text + "\n");`  
 like this)

another edit: ( sometimes on map restart map change it seems like the say callback is not being stopped when script it reloaded so it call onplayersay again so now theres 2 of the same func running 
(lol i got the callback running 7 times after setting callback once in init using map changes and restarts)

also sometimes when i type in chat server crashes)

when i return false in say callback the msg is hidden in chat like its suposed to
but then chat is not logged to log file
so whenever i hide a chat msg lets say its a cmd msg iw4m wont respond because nothing is printed

what im asking is can you make it so it always prints to log file or add another flag to set to allow log printing when hiding msg

**Comment by fedddddd** [comment]
Just use logprint
