### ISSUE TITLE
Update release

### ISSUE THREAD

**Issue by swifty-tekno** [fedddddd/iw5-gsc-utils#9]
i tried to clone the repo but my net trash and keeps timing out so i cant build the newest changes myself u mind updating the release when u have a chance thanks mate

**Comment by fedddddd** [comment]
Can you stop making issues for no reason? This isn't a web chat. I updated the release 10 hours ago.

**Comment by swifty-tekno** [comment]
sorry idk any other way to msg u
also i didnt see a change on releases tab from v1.2.4 when u updated it the second time so i didnt think it was updated
thx anyway sorry il stop putting stuff here

**Comment by fedddddd** [comment]
Just comment on an previous issue next time
